PREFIX ex:   <http://example.org/btc#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

SELECT ?minuto (AVG(?v) AS ?media)
WHERE {
  ?o a ex:BitcoinPriceObservation ;
     ex:priceValue ?v ;
     sosa:resultTime ?t .
  FILTER(?t >= NOW() - "PT1H"^^xsd:duration)
  BIND(SUBSTR(STR(?t),1,16) AS ?minuto)   # ← alias aqui
}
GROUP BY ?minuto
ORDER BY ?minuto
