PREFIX ex:<http://example.org/btc#>
PREFIX sosa:<http://www.w3.org/ns/sosa/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
SELECT ?prevTime ?prevVal ?currTime ?currVal ( ((?currVal-?prevVal)/?prevVal)*100 AS ?pct )
WHERE {
  ?prev a ex:BitcoinPriceObservation ;
        ex:priceValue ?prevVal ;
        sosa:resultTime ?prevTime .
  ?curr a ex:BitcoinPriceObservation ;
        ex:priceValue ?currVal ;
        sosa:resultTime ?currTime .
  FILTER(?currTime > ?prevTime && ?currTime <= ?prevTime + "PT1M"^^xsd:duration)
  FILTER(?currVal >= ?prevVal*1.05)
}
ORDER BY DESC(?currTime)
LIMIT 10